group 'com.amap.flutter.amap_flutter_map'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.9.1")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.amap.flutter.amap_flutter_map'

    compileSdk = 36


    defaultConfig {
        minSdkVersion 24
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    compileOnly 'com.amap.api:3dmap:8.1.0'
}

